/*
 * AutomatadegreeView.java
 */

package automatadegree;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class AutomatadegreeView extends FrameView {
String sub[]=new String [15];
 ImageIcon dfa;
    protected ImageIcon createImageIcon(String path,
                                               String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    public AutomatadegreeView(SingleFrameApplication app) {
        super(app);

        initComponents();

 
        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = AutomatadegreeApp.getApplication().getMainFrame();
            aboutBox = new AutomatadegreeAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        AutomatadegreeApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(automatadegree.AutomatadegreeApp.class).getContext().getActionMap(AutomatadegreeView.class, this);
        jButton1.setAction(actionMap.get("draw")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(automatadegree.AutomatadegreeApp.class).getContext().getResourceMap(AutomatadegreeView.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N

        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N

        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N

        jTextField6.setText(resourceMap.getString("jTextField6.text")); // NOI18N
        jTextField6.setName("jTextField6"); // NOI18N

        jTextField7.setText(resourceMap.getString("jTextField7.text")); // NOI18N
        jTextField7.setName("jTextField7"); // NOI18N

        jTextField8.setText(resourceMap.getString("jTextField8.text")); // NOI18N
        jTextField8.setName("jTextField8"); // NOI18N

        jTextField9.setText(resourceMap.getString("jTextField9.text")); // NOI18N
        jTextField9.setName("jTextField9"); // NOI18N

        jTextField10.setText(resourceMap.getString("jTextField10.text")); // NOI18N
        jTextField10.setName("jTextField10"); // NOI18N

        jTextField11.setText(resourceMap.getString("jTextField11.text")); // NOI18N
        jTextField11.setName("jTextField11"); // NOI18N

        jTextField12.setText(resourceMap.getString("jTextField12.text")); // NOI18N
        jTextField12.setName("jTextField12"); // NOI18N

        jTextField13.setText(resourceMap.getString("jTextField13.text")); // NOI18N
        jTextField13.setName("jTextField13"); // NOI18N

        jTextField14.setText(resourceMap.getString("jTextField14.text")); // NOI18N
        jTextField14.setName("jTextField14"); // NOI18N

        jTextField15.setText(resourceMap.getString("jTextField15.text")); // NOI18N
        jTextField15.setName("jTextField15"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel16.TabConstraints.tabTitle"), jLabel16); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel17.TabConstraints.tabTitle"), jLabel17); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel18.TabConstraints.tabTitle"), jLabel18); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel19.TabConstraints.tabTitle"), jLabel19); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel20.TabConstraints.tabTitle"), jLabel20); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel21.TabConstraints.tabTitle"), jLabel21); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel22.TabConstraints.tabTitle"), jLabel22); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel23.TabConstraints.tabTitle"), jLabel23); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel24.TabConstraints.tabTitle"), jLabel24); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel25.TabConstraints.tabTitle"), jLabel25); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel26.TabConstraints.tabTitle"), jLabel26); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel27.TabConstraints.tabTitle"), jLabel27); // NOI18N

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel28.TabConstraints.tabTitle"), jLabel28); // NOI18N

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel29.TabConstraints.tabTitle"), jLabel29); // NOI18N

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel30.TabConstraints.tabTitle"), jLabel30); // NOI18N

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jLabel31.TabConstraints.tabTitle"), jLabel31); // NOI18N

        jButton2.setAction(actionMap.get("clear")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(50, 50, 50)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(25, 25, 25)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12)
                            .addComponent(jTextField13)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15))
                        .addGap(45, 45, 45)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel5)
                                        .addGap(11, 11, 11)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N
        statusPanel.setPreferredSize(new java.awt.Dimension(1347, 10));

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addGap(179, 179, 179)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1002, Short.MAX_VALUE)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusMessageLabel)
                            .addComponent(statusAnimationLabel))
                        .addGap(20, 20, 20))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void draw() {
    
    sub[0]= jTextField1.getText();
    sub[1]=  jTextField2.getText();
    sub[2]=  jTextField3.getText();
    sub[3]=  jTextField14.getText();
    sub[4]=  jTextField5.getText();
    sub[5]=  jTextField6.getText();
    sub[6]=  jTextField7.getText();
    sub[7]=  jTextField8.getText();
    sub[8]=  jTextField9.getText();
    sub[9]=  jTextField10.getText();
    sub[10]=  jTextField11.getText();
    sub[11]=  jTextField12.getText();
    sub[12]=  jTextField13.getText();
    sub[13]=  jTextField14.getText();
     sub[14]=  jTextField15.getText();
     drawdfa();
    }
    public void drawdfa(){



int i= 0;
   while(!(sub[i]==null)){
     
    
    

        if( (sub[i].equals("taep") ||sub[i].equals("taetaep") || sub[i].equals("taetaetaep") || sub[i].equals("taetataep") ||  sub[i].equals("taetaxtaep" )||
             sub[i].equals("taettaep") || sub[i].equals("tataep") || sub[i].equals("tataetaep") || sub[i].equals("tatataep") ||sub[i].equals("tataxtaep")
             ||sub[i].equals("tattaep") || sub[i].equals("taxtaep" )|| sub[i].equals("taxtaetaep") ||sub[i].equals("taxtataep") ||sub[i].equals("tataxtaep")
            ||sub[i].equals("taxttaep" )||sub[i].equals("ttaep") ||sub[i].equals("ttaetaep") ||sub[i].equals("ttataep") ||sub[i].equals("ttaxtaep") ||sub[i].equals("tttaep")) ){


    if(i==14){ dfa = createImageIcon("images/sub/s16.jpg","DFA Base"); jLabel31.setIcon(dfa); JOptionPane.showMessageDialog(null, "Passed: completed subjects.."); }
     if(sub[i].equals("taep")){ dfa = createImageIcon("images/dfa/taep.jpg","DFA Base");
                             if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);} }
     if(sub[i].equals("taetaep")){ dfa = createImageIcon("images/dfa/taetaep.jpg","DFA Base");
                             if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taetaetaep")){dfa = createImageIcon("images/dfa/taetaetaep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);} }
     if(sub[i].equals("taetataep")){dfa = createImageIcon("images/dfa/taetataep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taetaxtaep")){dfa = createImageIcon("images/dfa/taetaxtaep.jpg","DFA Base");
                             if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taettaep")){dfa = createImageIcon("images/dfa/taettaep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}

     if(sub[i].equals("tataep")){dfa = createImageIcon("images/dfa/tataep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("tataetaep")){dfa = createImageIcon("images/dfa/tataetaep.jpg","DFA Base");
                             if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("tatataep")){dfa = createImageIcon("images/dfa/tatataep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("tataxtaep")){dfa = createImageIcon("images/dfa/tataxtaep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}

     if(sub[i].equals("tattaep")){dfa = createImageIcon("images/dfa/tattaep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taxtaep")){dfa = createImageIcon("images/dfa/taxtaep.jpg","DFA Base");
                            if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taxtaetaep")){dfa = createImageIcon("images/dfa/taxtaetaep.jpg","DFA Base");
                              if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taxtataep")){dfa = createImageIcon("images/dfa/taxtataep.jpg","DFA Base");
                            if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}
     if(sub[i].equals("taxtaxtaep")){dfa = createImageIcon("images/dfa/taxtaxtaep.jpg","DFA Base");
                            if(i==0) {jLabel16.setIcon(dfa);} if(i==1) {jLabel17.setIcon(dfa);} if(i==2) {jLabel18.setIcon(dfa);}if(i==3) {jLabel19.setIcon(dfa);} if(i==4) {jLabel20.setIcon(dfa);}if(i==5) {jLabel21.setIcon(dfa);}if(i==6) {jLabel22.setIcon(dfa);}if(i==7) {jLabel23.setIcon(dfa);}if(i==8) {jLabel24.setIcon(dfa);}if(i==9) {jLabel25.setIcon(dfa);}if(i==10) {jLabel26.setIcon(dfa);} if(i==11) {jLabel27.setIcon(dfa);}if(i==12) {jLabel28.setIcon(dfa);}if(i==13) {jLabel29.setIcon(dfa);}if(i==14) {jLabel30.setIcon(dfa);}}

        }
    if(!(sub[i].equals("taep") ||sub[i].equals("taetaep") || sub[i].equals("taetaetaep") || sub[i].equals("taetataep") ||  sub[i].equals("taetaxtaep" )||
             sub[i].equals("taettaep") || sub[i].equals("tataep") || sub[i].equals("tataetaep") || sub[i].equals("tatataep") ||sub[i].equals("tataxtaep")
             ||sub[i].equals("tattaep") || sub[i].equals("taxtaep" )|| sub[i].equals("taxtaetaep") ||sub[i].equals("taxtataep") ||sub[i].equals("tataxtaep")
            ||sub[i].equals("taxttaep" )||sub[i].equals("ttaep") ||sub[i].equals("ttaetaep") ||sub[i].equals("ttataep") ||sub[i].equals("ttaxtaep") ||sub[i].equals("tttaep")  )){

if(i==0){dfa = createImageIcon("images/sub/s1.jpg","DFA Base");
                              jLabel31.setIcon(dfa);
                              JOptionPane.showMessageDialog(null, "Faild :You must complete your states.");
                              break;
     }
     if(i==1){dfa = createImageIcon("images/sub/s2.jpg","DFA Base");
                              jLabel31.setIcon(dfa);
                              JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 14 subjects"); break;
     }
     if(i==2){dfa = createImageIcon("images/sub/s3.jpg","DFA Base");
                              jLabel31.setIcon(dfa);JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 13 subjects"); break;
     }
     
     if(i==3){dfa = createImageIcon("images/sub/s4.jpg","DFA Base");
                              jLabel31.setIcon(dfa);JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 12 subjects");
     }
    if(i==4){dfa = createImageIcon("images/sub/s5.jpg","DFA Base");
                              jLabel31.setIcon(dfa);
                              JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 11 subjects"); break;
     }
     if(i==5){dfa = createImageIcon("images/sub/s6.jpg","DFA Base");
                              jLabel31.setIcon(dfa);
                              JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 10 subjects"); break;
     }
    if(i==6){dfa = createImageIcon("images/sub/s7.jpg","DFA Base");
                              jLabel31.setIcon(dfa);JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 9 subjects"); break;
     }
     if(i==7){dfa = createImageIcon("images/sub/s8.jpg","DFA Base");
                              jLabel31.setIcon(dfa); JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 8 subjects"); break;
     }
if(i==8){dfa = createImageIcon("images/sub/s9.jpg","DFA Base");
                              jLabel31.setIcon(dfa);   JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 7 subjects"); break;
     }
if(i==9){dfa = createImageIcon("images/sub/s10.jpg","DFA Base");
                              jLabel31.setIcon(dfa);   JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 6 subjects"); break;
     }


if(i==10){dfa = createImageIcon("images/sub/s11.jpg","DFA Base");
                              jLabel31.setIcon(dfa);  JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 5 subjects");   break;
     }if(i==11){dfa = createImageIcon("images/sub/s12.jpg","DFA Base");
                              jLabel31.setIcon(dfa);   JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 4 subjects");   break;
     }
if(i==12){dfa = createImageIcon("images/sub/s13.jpg","DFA Base");
                              jLabel31.setIcon(dfa);  JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 3 subjects");    break;
     }
if(i==13){dfa = createImageIcon("images/sub/s14.jpg","DFA Base");
                              jLabel31.setIcon(dfa);  JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 2 subjects");    break;
     }

if(i==14){dfa = createImageIcon("images/sub/s15.jpg","DFA Base");
                              jLabel31.setIcon(dfa);   JOptionPane.showMessageDialog(null, "Faild : Incomplete subjects..you have to complete more 1 subjects");  break;
     }


 

} i++; }
    }

    @Action
    public void clear() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    jTextField10.setText("");
    jTextField11.setText("");
    jTextField12.setText("");
    jTextField13.setText("");
    jTextField14.setText("");
    jTextField15.setText("");

     jLabel16.setIcon(null);
     jLabel17.setIcon(null);
     jLabel18.setIcon(null);
     jLabel19.setIcon(null);
     jLabel20.setIcon(null);
     jLabel21.setIcon(null);
     jLabel22.setIcon(null);
     jLabel23.setIcon(null);
     jLabel24.setIcon(null);
     jLabel25.setIcon(null);
     jLabel26.setIcon(null);
     jLabel27.setIcon(null);
     jLabel28.setIcon(null);
     jLabel29.setIcon(null);
     jLabel30.setIcon(null);
     jLabel31.setIcon(null);
     


    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
